default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: pictweet2_development

test:
  <<: *default
  database: pictweet2_test


production:
  <<: *default
  database: pictweet2_production
  username: pictweet2
  password: <%= ENV['PICTWEET2_DATABASE_PASSWORD'] %>
